const colorsArray=['red darken-1',
'red darken-2',
'red darken-3',
'red darken-4',
'pink darken-1',
'pink darken-2',
'pink darken-3',
'pink darken-4',
'purple darken-1',
'purple darken-2',
'purple darken-3',
'purple darken-4',
'deep-purple darken-1',
'deep-purple darken-2',
'deep-purple darken-3',
'deep-purple darken-4',
'indigo darken-1',
'indigo darken-2',
'indigo darken-3',
'indigo darken-4',
'blue darken-1',
'blue darken-2',
'blue darken-3',
'blue darken-4',
'light-blue darken-1',
'light-blue darken-2',
'light-blue darken-3',
'light-blue darken-4',
'cyan darken-1',
'cyan darken-2',
'cyan darken-3',
'cyan darken-4',
'teal darken-1',
'teal darken-2',
'teal darken-3',
'teal darken-4',
'green darken-1',
'green darken-2',
'green darken-3',
'green darken-4',
'light-green darken-1',
'light-green darken-2',
'light-green darken-3',
'light-green darken-4',
'lime darken-1',
'lime darken-2',
'lime darken-3',
'lime darken-4',
'yellow darken-1',
'yellow darken-2',
'yellow darken-3',
'yellow darken-4',
'amber darken-1',
'amber darken-2',
'amber darken-3',
'amber darken-4',
'orange darken-1',
'orange darken-2',
'orange darken-3',
'orange darken-4',
'deep-orange darken-1',
'deep-orange darken-2',
'deep-orange darken-3',
'deep-orange darken-4',
'brown darken-1',
'brown darken-2',
'brown darken-3',
'brown darken-4',
'blue-grey darken-1',
'blue-grey darken-2',
'blue-grey darken-3',
'blue-grey darken-4',
'grey darken-1',
'grey darken-2',
'grey darken-3',
'grey darken-4']

export default {
    pickColor: function() {
      return colorsArray[Math.floor(Math.random() * colorsArray.length)];
    }
}

